### ISSUE TITLE
ReWarp Crashes on the A1222 (Tabor, e500 core)

### ISSUE THREAD

**Issue by ksdhans** [Sakura-IT/ReWarp#12]
ReWarp crashes on the A1222 when executing mtsc, which the e500 core **does** not support. It looks like it's using the wrong initialization code. This is with the latest version compiled by Jenkins (#73).

**Comment by ksdhans** [comment]
Here's the crash log:
[Crashlog_Wipeout_2020-12-26_01-03-47.txt](https://github.com/Sakura-IT/ReWarp/files/5741996/Crashlog_Wipeout_2020-12-26_01-03-47.txt)

**Comment by ksdhans** [comment]
Here's a fix:
[ReWarp_A1222_fix.zip](https://github.com/Sakura-IT/ReWarp/files/5742792/ReWarp_A1222_fix.zip)

NOTE: I had to zip up the file, because GitHub doesn't like *.diff files.

**Comment by rkujawa** [comment]
@ksdhans Thanks! Looks good to me.

@DvdBoon Shall I apply the patch as-is?

**Comment by DvdBoon** [comment]
The Tabor was not something this library was initially coded for. But indeed, e500 cores are missing the segment registers and as such mtsr is not supported. @rkujawa The patch can be applied as is.
