### ISSUE TITLE
Distorted graphics with Warp3D

### ISSUE THREAD

**Issue by DvdBoon** [Sakura-IT/ReWarp#3]
Certain Warp3D games (glQuake) and demos (ByNight and Saluco from Encore) give graphic corruption. This was tested on an Amiga 4000T with a Voodoo4 and AmigaOS 4.1FE.

This is fixed by applying the patchwarp3d program from Alain Thellier on Aminet. The offending function has been tracked down to DrawElements.

This is to keep track of a permanent fix.

**Comment by DvdBoon** [comment]
This will be tracked further by the ReWarp3DPPC issue tracker.

**Comment by rkujawa** [comment]
See Sakura-IT/ReWarp3DPPC#1 .

**Comment by DvdBoon** [comment]
I changed titles. One is for Radeon and the other for Voodoo4. The Voodoo
driver has not been worked on since 2005 (or so I have been told). Root of
the problem could be different so I like to track them seperately. Also the
platform is differen (Sam vs Classic).

2016-08-22 12:00 GMT+02:00 Radosław Kujawa notifications@github.com:
